version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    volumes:
      - ./cassandra-init:/docker-entrypoint-initdb.d

volumes:
  cassandra-data:
